fix: update image commits
StatCan/kubeflow-manifest pull request #44
Opened 2020-10-07 15:33 UTC by saffaalvi

Resolves https://github.com/StatCan/kubeflow-manifest/issues/43

2020-10-07 15:50 UTC, ca-scribner submitted a review, later dismissed

2020-10-19 21:07 UTC, brendangadd requested changes

2020-10-19 21:07 UTC, brendangadd commented on kustomize/jupyter-web-app/base/config-map.yaml
> +        value: k8scc01covidacr.azurecr.io/minimal-notebook-cpu:59c4e46f87f41a8649a573e6da20035ac04e3c44
This tag doesn't exist in the list below.

2020-10-21 16:32 UTC, brendangadd approved these changes

2020-10-21 16:32 UTC, merged