fix: add KUBECOST_URL to jupyter-web-app deployment
StatCan/kubeflow-manifest pull request #51
Opened 2020-10-16 19:50 UTC by saffaalvi

Resolves https://github.com/StatCan/kubeflow-manifest/issues/50

2020-10-19 16:04 UTC, brendangadd requested changes

2020-10-19 16:04 UTC, brendangadd commented on kustomize/jupyter-web-app/base/params.env
> +KUBECOST_URL=http://0.0.0.0:9090
This needs to be the actual in-cluster URL.

2020-10-19 22:35 UTC, zachomedia approved these changes
LGTM

2020-10-19 22:37 UTC, zachomedia requested changes

2020-10-19 22:37 UTC, zachomedia commented on kustomize/jupyter-web-app/base/deployment.yaml
> +              key: KUBECOST_URL
This isn't output into the config map. I'm looking further

2020-10-19 22:39 UTC, zachomedia commented on kustomize/jupyter-web-app/base/deployment.yaml
> +              key: KUBECOST_URL
Never mind, I see it gets written out

2020-10-19 22:39 UTC, zachomedia approved these changes

2020-10-20 16:32 UTC, brendangadd approved these changes

2020-10-20 16:32 UTC, merged